/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as GuardadosRouteImport } from './routes/guardados'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ViajesRouteImport } from './routes/viajes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadosRoute = GuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesRoute = ViajesRouteImport.update({
  id: '/viajes',
  path: '/viajes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/explorar': typeof ExplorarRoute
  '/guardados': typeof GuardadosRoute
  '/perfil': typeof PerfilRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/explorar': typeof ExplorarRoute
  '/guardados': typeof GuardadosRoute
  '/perfil': typeof PerfilRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/explorar': typeof ExplorarRoute
  '/guardados': typeof GuardadosRoute
  '/perfil': typeof PerfilRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ajustes' | '/explorar' | '/guardados' | '/perfil' | '/viajes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajustes' | '/explorar' | '/guardados' | '/perfil' | '/viajes'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/explorar'
    | '/guardados'
    | '/perfil'
    | '/viajes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  ExplorarRoute: typeof ExplorarRoute
  GuardadosRoute: typeof GuardadosRoute
  PerfilRoute: typeof PerfilRoute
  ViajesRoute: typeof ViajesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardados': {
      id: '/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof GuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes': {
      id: '/viajes'
      path: '/viajes'
      fullPath: '/viajes'
      preLoaderRoute: typeof ViajesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  ExplorarRoute: ExplorarRoute,
  GuardadosRoute: GuardadosRoute,
  PerfilRoute: PerfilRoute,
  ViajesRoute: ViajesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
